Repository CSI-SCT-SB/CSL-204-Operating-Systems-Lab, pull requests merged in 2022-10, with the labels that each got.

#1 Create _5.ProducerConsumer.c
  _5.ProducerConsumer.c
Labels: hacktoberfest_accepted

#2 _8.Memoryallocation.c
  _10.bankers.c
  _11a.diskfcfs.c
  _11b.diskscan.c
  _11c.diskcscan.c
  _4.sharedmemory.c
  _6a.fcfs.c
  _6b.sjf.c
  _6c.priority.c
  _6d.rr.c
  _8.Memoryallocation.c
  _9a.fifo.c
  _9b.lru.c
Labels: good first issue, hacktoberfest_accepted, excellent

#3 Create _7.gantt.c
  _7.gantt.c
Labels: hacktoberfest_accepted

#5 Create lfu.c (OS LAB-page replacement)
  _9c.lfu.c
Labels: enhancement, good first issue, hacktoberfest_accepted

#4 Create _1.fibonacci.sh
  _2.fibonacci.sh
  _2.largest.sh
Labels: hacktoberfest_accepted

#6 Experiment 3
  _3.fork.getpid.execlp.c
  _3.openclose.c
  _3.openreaddir.c
  _3.stat.c
  _3.wait.c
Labels: hacktoberfest_accepted

#7 factorial using shell
  _2.factorial.sh
Labels: good first issue, hacktoberfest_accepted

#8 Add files via upload
  Optimal_PageReplacement.c
Labels: hacktoberfest_accepted

#9 Add files via upload
  sequentialfilealloc.c
Labels: hacktoberfest_accepted
